export {default as HomePage} from "./HomePage"
export {default as AboutUs} from "./About/AboutUs"
export {default as AboutMission} from "./About/About_mission"
export {default as FacultyAndStaff} from "./About/FacultyStaff"
export {default as About_Facility} from "./About/About_Facility"
export {default as AboutTestimonial} from "./About/About_Testimonial"
export {default as ContactUsPage} from "./ContactUsPage"
export {default as AcademicHome} from "./Academics/AcademicHome"